// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function($) {
    var env, manager;
    env = {
      gamediv: $('#gameDiv'),
      description: {}
    };
    manager = new GameManager(env);
    window.Manager = manager;
  });

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
