// Generated by CoffeeScript 1.6.3
(function() {
  var PlayerCodeEditor, _base,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_base = String.prototype).startsWith == null) {
    _base.startsWith = function(str) {
      return this.lastIndexOf(str, 0) === 0;
    };
  }

  window.EditorManager = (function() {
    /*
        Manages the code editor.
    */

    function EditorManager(editorDivId, editorConfig, codeConfig) {
      this.editorDivId = editorDivId;
      this.editorConfig = editorConfig;
      this.codeConfig = codeConfig;
      this.onEditorClick = __bind(this.onEditorClick, this);
      this.onEditorCursorMove = __bind(this.onEditorCursorMove, this);
      this.onStudentCodeChange = __bind(this.onStudentCodeChange, this);
      this.resetEditor = __bind(this.resetEditor, this);
      this.commands = this.editorConfig.commands;
      this.setUpEditor();
      return;
    }

    EditorManager.prototype.getStudentCode = function() {
      return this.editor.getStudentCode();
    };

    EditorManager.prototype.setUpEditor = function() {
      /*
          Builds the HTML for, and sets up the functionality of,
          the player code editor.
      */

      var buttonField, editorDiv;
      editorDiv = jQuery("#" + this.editorDivId);
      editorDiv.append('<div id="ace-editor"></div>');
      if (this.editorConfig.buttons.length !== 0) {
        buttonField = jQuery('<div>', {
          id: 'buttons'
        });
        if ($.inArray('switchUp', this.editorConfig.buttons) !== -1) {
          buttonField.append('<button id="switchUp">Up</button>');
        }
        if ($.inArray('switchDown', this.editorConfig.buttons) !== -1) {
          buttonField.append('<button id="switchDown">Down</button>');
        }
        if ($.inArray('deleteLine', this.editorConfig.buttons) !== -1) {
          buttonField.append('<button id="deleteLine">Delete</button>');
        }
        if ($.inArray('insertButtons', this.editorConfig.buttons) !== -1) {
          buttonField.append('<br />');
          buttonField.append(jQuery('<div>', {
            id: 'insertButtons'
          }).get(0));
        }
        buttonField.append('<br />');
        editorDiv.append(buttonField.get(0));
      }
      editorDiv.append('<div id="parameter-pop-up" class="pop-up-container"></div>');
      this.editor = new PlayerCodeEditor('ace-editor', this.commands, this.codeConfig.initial, this.codeConfig.show, this.codeConfig.prefix, this.codeConfig.postfix, this.editorConfig.freeformEditting);
      this.interpreter = new CodeInterpreter(this.commands);
      this.setUpInsertButtons();
      this.addEventListeners();
      return this.onStudentCodeChange();
    };

    EditorManager.prototype.setUpInsertButtons = function() {
      /*
          Inserts a button for each command of the game to the html field
          with the id of 'insertButtons'.
      */

      var button, buttonField, buttons, codeEditor, command, line, usesRemaining;
      if ($.inArray('insertButtons', this.editorConfig.buttons) === -1) {
        return;
      }
      buttonField = jQuery('#insertButtons');
      buttons = [];
      for (command in this.commands) {
        line = this.editor.createBlankFunctionHeader(command) + ';';
        usesRemaining = this.commands[command]['usesRemaining'];
        codeEditor = this.editor;
        button = jQuery('<button>', {
          id: command,
          value: command,
          text: "" + line + ": " + usesRemaining,
          click: function(e) {
            (codeEditor.button(codeEditor.usesCurrentRow(codeEditor.usesTextDocument(codeEditor.insertLine)))).call(codeEditor, codeEditor.createNamedArguments({
              line: e.currentTarget.value
            }));
            return false;
          }
        });
        buttons.push(button.get(0));
      }
      buttonField.append(buttons);
    };

    EditorManager.prototype.addEventListeners = function() {
      var ed;
      ed = this.editor;
      if ($.inArray('switchUp', this.editorConfig.buttons) !== -1) {
        jQuery('#switchUp').click(ed.button(ed.usesCurrentPosition(ed.switchUp)));
      }
      if ($.inArray('switchDown', this.editorConfig.buttons) !== -1) {
        jQuery('#switchDown').click(ed.button(ed.usesCurrentPosition(ed.switchDown)));
      }
      if ($.inArray('deleteLine', this.editorConfig.buttons) !== -1) {
        jQuery('#deleteLine').click(ed.button(ed.usesTextDocument(ed.usesCurrentRow(ed.deleteLine))));
      }
      ed.onChangeListener(this.onStudentCodeChange);
      ed.onClickListener(this.onEditorClick);
      ed.onCursorMoveListener(this.onEditorCursorMove);
    };

    EditorManager.prototype.resetEditor = function() {
      (this.editor.button(this.editor.resetState))();
    };

    EditorManager.prototype.onStudentCodeChange = function() {
      /*
          When the student code changes, run it through the
          interpreter to figure out commands remaining.
      */

      var remaining;
      remaining = this.interpreter.scanText(this.editor.getStudentCode());
      this.UpdateCommandsStatus(remaining);
    };

    EditorManager.prototype.UpdateCommandsStatus = function(remaining) {
      /*
          Updates the number of commands remaining for each command.
      */

      var button, buttonField, command, line, usesRemaining;
      buttonField = jQuery('#insertButtons');
      for (command in this.commands) {
        button = buttonField.find("#" + command);
        line = this.editor.createBlankFunctionHeader(command);
        usesRemaining = remaining[command];
        if (usesRemaining <= 0) {
          button.attr('disabled', true);
        } else {
          button.attr('disabled', false);
        }
        button.text("" + line + ": " + usesRemaining);
      }
    };

    EditorManager.prototype.onEditorCursorMove = function(cursorEvent) {
      if (this.parameterPopUp === void 0) {
        this.parameterPopUp = jQuery('#parameter-pop-up');
      }
      return this.parameterPopUp.hide();
    };

    EditorManager.prototype.onEditorClick = function(inBounds, clickEvent) {
      /*
          When the editor is clicked, we may or may not
          want to pop up a div for students to enter
          parameters into.
          Return true: continue event propogation
          Return false: stop event propogation
      */

      var button, command, editorOffset, gutterOffset, i, id, line, manager, numberOfInputs, row, rowLength, _i, _ref;
      if (this.parameterPopUp === void 0) {
        this.parameterPopUp = jQuery('#parameter-pop-up');
      }
      if (inBounds) {
        row = clickEvent.$pos.row;
        line = clickEvent.editor.getSession().getLine(row);
        rowLength = line.length;
        if (rowLength === 0) {
          this.parameterPopUp.hide();
          return true;
        }
        command = this.interpreter.identifyCommand(line);
        if (command === null) {
          this.parameterPopUp.hide();
          return true;
        }
        numberOfInputs = this.commands[command]['inputs'];
        if (numberOfInputs === 0) {
          this.parameterPopUp.hide();
          return true;
        }
        this.parameterPopUp.empty();
        this.parameterPopUp.append('(');
        for (i = _i = 1; _i <= numberOfInputs; i = _i += 1) {
          id = "" + command + "-parameter-" + i;
          this.parameterPopUp.append("<input id='" + id + "' type='text' size='5' class='pop-up-inside'>");
          if (i !== numberOfInputs) {
            this.parameterPopUp.append(',');
            jQuery("#" + id).keypress(function(e) {
              if (e.which === 13) {
                setTimeout((function() {
                  jQuery(e.currentTarget).next().focus();
                }), 0);
                return false;
              }
              return true;
            });
          } else {
            manager = this;
            jQuery("#" + id).keypress(function(e) {
              if (e.which === 13) {
                setTimeout((function() {
                  manager.popUpEditLine(row, command);
                }), 0);
                return false;
              }
              return true;
            });
          }
        }
        this.parameterPopUp.append(')');
        button = jQuery('<button>', {
          id: 'editLine',
          text: 'Edit',
          "class": 'pop-up-inside',
          click: this.popUpEditLine.bind(this, row, command)
        });
        this.parameterPopUp.append(button.get(0));
        editorOffset = jQuery('#ace-editor').position();
        gutterOffset = this.editor.editor.renderer.$gutterLayer.gutterWidth + ((_ref = this.editor.editor.renderer.$gutterLayer.$padding) != null ? _ref.left : void 0);
        this.parameterPopUp.css('top', row * 12 + editorOffset.top - 3);
        this.parameterPopUp.css('left', rowLength * 6 + gutterOffset + editorOffset.left);
        this.parameterPopUp.show();
        setTimeout((function() {
          jQuery("#" + command + "-parameter-" + 1).focus();
        }), 0);
        return false;
      } else {
        this.parameterPopUp.hide();
      }
      return true;
    };

    EditorManager.prototype.popUpEditLine = function(row, command) {
      var ed, i, line, _i, _ref;
      if (this.parameterPopUp === void 0) {
        this.parameterPopUp = jQuery('#parameter-pop-up');
      }
      line = "" + command + "(";
      for (i = _i = 1, _ref = this.commands[command]['inputs']; _i <= _ref; i = _i += 1) {
        line += jQuery("#parameter-pop-up #" + command + "-parameter-" + i).val();
        if (i !== this.commands[command]['inputs']) {
          line += ', ';
        }
      }
      line += ');';
      ed = this.editor;
      (ed.button(ed.usesTextDocument(ed.editLine))).call(ed, ed.createNamedArguments({
        newLine: line,
        editRow: row
      }));
      this.parameterPopUp.hide();
    };

    return EditorManager;

  })();

  PlayerCodeEditor = (function() {
    /*
        Creates and provides functionality for an Ace editor representing player's code.
    */

    function PlayerCodeEditor(editorDivId, commands, codeText, wrapCode, codePrefix, codeSuffix, freeEdit) {
      this.editorDivId = editorDivId;
      this.commands = commands;
      this.wrapCode = wrapCode;
      this.codePrefix = codePrefix;
      this.codeSuffix = codeSuffix;
      this.freeEdit = freeEdit;
      /*
          Sets internal variables, the default text and buttons
          and their event handlers.
      */

      this.editor = ace.edit(this.editorDivId);
      this.editSession = this.editor.getSession();
      this.editSession.setMode('ace/mode/java');
      this.editSession.setUseSoftTabs(true);
      this.editor.setReadOnly(!this.freeEdit);
      if (this.wrapCode) {
        this.codeText = this.codePrefix + codeText + '\n' + this.codeSuffix;
      } else {
        this.codePrefix = "";
        this.codeSuffix = "";
        this.codeText = codeText;
      }
      this.codePrefixLength = codePrefix.split('\n').length - 1;
      this.codeSuffixLength = codeSuffix.split('\n').length - 1;
      this.enableKeyboardShortcuts();
      this.resetState();
      this.editor.focus();
    }

    PlayerCodeEditor.prototype.getStudentCode = function() {
      return this.editor.getValue();
    };

    PlayerCodeEditor.prototype.enableKeyboardShortcuts = function() {
      /*
          Not currently enabled as it would be difficult to prevent
          keyboard shortcuts from changing uneditable areas.
      */

    };

    PlayerCodeEditor.prototype.onChangeListener = function(callback) {
      this.editor.on('change', callback);
    };

    PlayerCodeEditor.prototype.onClickListener = function(callback) {
      var _this = this;
      this.editor.on('click', (function(clickEvent) {
        var inBounds;
        inBounds = true;
        if (clickEvent.$pos.row < _this.codePrefixLength || clickEvent.$pos.row >= _this.editSession.getLength() - _this.codeSuffixLength) {
          inBounds = false;
        }
        return callback(inBounds, clickEvent);
      }));
    };

    PlayerCodeEditor.prototype.onCursorMoveListener = function(callback) {
      this.editSession.getSelection().on('changeCursor', callback);
    };

    PlayerCodeEditor.prototype.switchUp = function(_arg) {
      var currentColumn, currentRow, maxRow;
      currentRow = _arg.currentRow, currentColumn = _arg.currentColumn;
      maxRow = this.editSession.getLength();
      if (currentRow - 1 < this.codePrefixLength || currentRow >= maxRow - this.codeSuffixLength) {
        return;
      }
      if (currentRow > 0) {
        this.editSession.moveLinesUp(currentRow, currentRow);
        this.editor.gotoLine(currentRow, currentColumn, false);
      }
    };

    PlayerCodeEditor.prototype.switchDown = function(_arg) {
      var currentColumn, currentRow, maxRow;
      currentRow = _arg.currentRow, currentColumn = _arg.currentColumn;
      maxRow = this.editSession.getLength();
      if (currentRow + 1 >= maxRow - this.codeSuffixLength || currentRow < this.codePrefixLength) {
        return;
      }
      if (currentRow < maxRow - 1) {
        this.editSession.moveLinesDown(currentRow, currentRow);
        this.editor.gotoLine(currentRow + 2, currentColumn, false);
      }
    };

    PlayerCodeEditor.prototype.deleteLine = function(_arg) {
      var currentRow, line, maxRow, text;
      text = _arg.text, currentRow = _arg.currentRow;
      maxRow = this.editSession.getLength();
      if (currentRow >= maxRow - this.codeSuffixLength || currentRow < this.codePrefixLength) {
        return;
      }
      line = text.getLine(currentRow);
      if (text.getLength() === 1) {
        text.insertLines(currentRow + 1, ["\n"]);
        text.removeNewLine(currentRow);
      }
      text.removeLines(currentRow, currentRow);
    };

    PlayerCodeEditor.prototype.insertLine = function(_arg) {
      var currentRow, line, maxRow, printLine, text;
      text = _arg.text, line = _arg.line, currentRow = _arg.currentRow;
      maxRow = this.editSession.getLength();
      if (currentRow + 1 < this.codePrefixLength || currentRow + 1 >= maxRow - (this.codeSuffixLength - 1)) {
        return;
      }
      printLine = (this.createBlankFunctionHeader(line)) + ';';
      text.insertLines(currentRow + 1, [printLine]);
      if (text.getLength() === 2 && text.getLine(currentRow) === "") {
        text.removeNewLine(currentRow);
      }
      this.editor.gotoLine(currentRow + 2, 0, false);
    };

    PlayerCodeEditor.prototype.editLine = function(_arg) {
      var editRow, maxRow, newLine, position, text;
      text = _arg.text, editRow = _arg.editRow, newLine = _arg.newLine;
      maxRow = this.editSession.getLength();
      if (editRow + 1 < this.codePrefixLength || editRow + 1 >= maxRow - (this.codeSuffixLength - 1)) {
        return;
      }
      position = this.editor.getCursorPosition();
      text.insertLines(editRow, [newLine]);
      text.removeLines(editRow + 1, editRow + 1);
      this.editor.moveCursorToPosition(position);
    };

    PlayerCodeEditor.prototype.resetState = function() {
      /*
          Resets the text displayed in the editor,
          the commands used counts, and other internal variables.
      */

      this.editor.setValue(this.codeText);
      this.editor.clearSelection();
      this.editor.gotoLine(0, 0, false);
      this.reIndentCode();
    };

    PlayerCodeEditor.prototype.reIndentCode = function() {
      var currentIndent, currentRow, mode, position, text, thisLine, thisLineIndent, _i, _ref;
      position = this.editor.getCursorPosition();
      text = this.editSession.getDocument();
      mode = this.editSession.getMode();
      for (currentRow = _i = 0, _ref = this.editSession.getLength(); _i < _ref; currentRow = _i += 1) {
        if (currentRow === 0) {
          continue;
        }
        thisLineIndent = mode.getNextLineIndent(this.editSession.getState(currentRow - 1), this.editSession.getLine(currentRow - 1), this.editSession.getTabString());
        thisLine = this.editSession.getLine(currentRow);
        currentIndent = /^\s*/.exec(thisLine)[0];
        if (currentIndent !== thisLineIndent) {
          thisLine = thisLineIndent + thisLine.trim();
        }
        text.insertLines(currentRow, [thisLine]);
        text.removeLines(currentRow + 1, currentRow + 1);
        mode.autoOutdent(this.editSession.getState(currentRow), this.editSession, currentRow);
      }
      this.editor.moveCursorToPosition(position);
      this.editor.clearSelection();
    };

    PlayerCodeEditor.prototype.createBlankFunctionHeader = function(command) {
      /*
          Creates a function header with __ for parameters.
          eg go(__)
      */

      var i, numberOfInputs, underscoresForInputs, _i;
      numberOfInputs = this.commands[command]['inputs'];
      underscoresForInputs = "";
      for (i = _i = 1; _i <= numberOfInputs; i = _i += 1) {
        underscoresForInputs += '__';
        if (i !== numberOfInputs) {
          underscoresForInputs += ', ';
        }
      }
      return "" + command + "(" + underscoresForInputs + ")";
    };

    PlayerCodeEditor.prototype.button = function(func) {
      /*
          This is a wrapper for the functions which are tied to buttons.
          It restores focus to the editor after the button has been pressed.
      */

      var playerCodeEditor;
      playerCodeEditor = this;
      return function() {
        if (arguments.length !== 0 && playerCodeEditor.detectNamedArgument(arguments[0])) {
          func.apply(playerCodeEditor, arguments);
        } else {
          func.call(playerCodeEditor);
        }
        playerCodeEditor.reIndentCode();
        playerCodeEditor.editor.focus();
        return false;
      };
    };

    PlayerCodeEditor.prototype.usesCurrentRow = function(func) {
      /*
          This is a wrapper for the functions which need to know the current row.
          It retrieves the current row and passes it to the function.
      */

      var playerCodeEditor;
      playerCodeEditor = this;
      return function() {
        var currentRow;
        currentRow = playerCodeEditor.editor.getCursorPosition().row;
        this.addNamedArguments(arguments, {
          currentRow: currentRow
        });
        if (arguments.length !== 0 && playerCodeEditor.detectNamedArgument(arguments[0])) {
          func.apply(playerCodeEditor, arguments);
        } else {
          func.call(playerCodeEditor);
        }
        return false;
      };
    };

    PlayerCodeEditor.prototype.usesCurrentPosition = function(func) {
      /*
          This is a wrapper for the functions which need to know the cursor's row and column
          It retrieves the current row and the current column and passes them to the function.
      */

      var playerCodeEditor;
      playerCodeEditor = this;
      return function() {
        var cursorPosition;
        cursorPosition = playerCodeEditor.editor.getCursorPosition();
        this.addNamedArguments(arguments, {
          currentRow: cursorPosition.row,
          currentColumn: cursorPosition.column
        });
        if (arguments.length !== 0 && playerCodeEditor.detectNamedArgument(arguments[0])) {
          func.apply(playerCodeEditor, arguments);
        } else {
          func.call(playerCodeEditor);
        }
        return false;
      };
    };

    PlayerCodeEditor.prototype.usesTextDocument = function(func) {
      /*
          This is a wrapper for functions which edit the text in the editor directly.
          It gets a reference to the text and passes it to the function.
      */

      var playerCodeEditor;
      playerCodeEditor = this;
      return function() {
        var text;
        text = playerCodeEditor.editSession.getDocument();
        this.addNamedArguments(arguments, {
          text: text
        });
        if (arguments.length !== 0 && playerCodeEditor.detectNamedArgument(arguments[0])) {
          func.apply(playerCodeEditor, arguments);
        } else {
          func.call(playerCodeEditor);
        }
        return false;
      };
    };

    PlayerCodeEditor.prototype.addNamedArguments = function(originalArguments, argumentDictionary) {
      /*
          Adds the named arguments to the original arguments.
          Makes changes to originalArguments, returns nothing.
      */

      var argument, argumentFound;
      if (originalArguments.length === 0) {
        originalArguments[originalArguments.length++] = this.createNamedArguments(argumentDictionary);
      } else {
        argumentFound = false;
        for (argument in originalArguments) {
          if (this.detectNamedArgument(originalArguments[argument])) {
            jQuery.extend(true, originalArguments[argument], argumentDictionary);
            argumentFound = true;
            break;
          }
        }
        if (!argumentFound) {
          originalArguments[originalArguments.length++] = this.createNamedArguments(argumentDictionary);
        }
      }
    };

    PlayerCodeEditor.prototype.createNamedArguments = function(argumentDictionary) {
      /*
          Takes in an object of key-value pairs,
          returns an object of the Named Arguments format.
      */

      argumentDictionary['namedArgumentsFlag'] = true;
      return argumentDictionary;
    };

    PlayerCodeEditor.prototype.detectNamedArgument = function(argument) {
      /*
          Returns whether or not the argument is of the namedArguments format.
      */

      if (argument === null) {
        return false;
      }
      if (typeof argument !== 'object') {
        return false;
      }
      if (!('namedArgumentsFlag' in argument)) {
        return false;
      }
      if (argument['namedArgumentsFlag'] !== true) {
        return false;
      }
      return true;
    };

    return PlayerCodeEditor;

  })();

}).call(this);

/*
//@ sourceMappingURL=playerCodeEditor.map
*/
